config/routes.rb
Rails.application.routes.draw do
  
  resources :projects
  resources :roles
  resources :cells
  get 'directories/index'

  get 'directories/show'

  devise_for :users

  resources :questions do
    member do
      put "like", to: "questions#upvote"
      put "dislike", to: "questions#downvote"
    end
  end
  
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end


  get '/home', to: "home#index"
  root :to => "home#index"
  

  post "/post_comment/", to: "post_comments#create", as: :post_comments
  post "/question_comment/", to: "question_comments#create", as: :question_comments

  #diretorias
  get "/directories", to: "directories#index", as: :directories
  get "/directory/:id", to: "directories#show", as: :directory
  get "directories/new", to: "directories#new", as: :new_directory
  post "directories/", to: "directories#create", as: :create_directory
  delete "directory/:id", to: "directories#destroy", as: :remove_directory


  post "/enter_directory", to: "directories#enter_directory", as: :enter_directory
  post "/fusion_ask", to: "directories#fusion_ask", as: :fusion_ask
  get "/fusion_ask_requests", to: "directories#fusion_ask_request", as: :fusion_ask_request
  post "/fusion_ask_accept", to: "directories#fusion_ask_accept", as: :fusion_ask_accept
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #cell
  post "/participate_cell", to: "cells#participate_cell", as: :participate_cell

  #projects
  post "/enter_project", to: "projects#enter_project", as: :enter_project
  post "/accept_request", to: "projects#accept_project_requests", as: :accept_project_requests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cell.rb
class Cell < ApplicationRecord
    has_many :users

    has_many :user_cells
    has_many :users, through: :user_cells
    
end

app/models/directory.rb
class Directory < ApplicationRecord
    has_many :users
    has_many :fusion_asks
end

app/models/fusion_ask.rb
class FusionAsk < ApplicationRecord
  belongs_to :user
  belongs_to :directory
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :delete_all
  acts_as_votable
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :user_projects
    has_many :users, through: :user_projects

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :question_comments, dependent: :delete_all
  acts_as_votable
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  has_many :questions

  has_many :post_comments

  belongs_to :directory, optional: true
  has_many :fusion_asks
  
  has_many :user_cells, dependent: :delete_all
  has_many :cells, through: :user_cells
  
  has_many :user_projects, dependent: :delete_all
  has_many :projects, through: :user_projects


  acts_as_voter

end

app/models/user_cell.rb
class UserCell < ApplicationRecord
  belongs_to :user
  belongs_to :cell
end

app/models/user_project.rb
class UserProject < ApplicationRecord

  belongs_to :user
  belongs_to :project
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index

    @user = current_user
    @posts = @user.posts
    @questions = @user.questions
    
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/home/index.html.erb
<section class="artigos">
    <h1>Perfil</h1>
    <div class="containerindex">
        

        <%if !@user.directory_id.nil? %>
            <h3>Diretoria: <%= @user.directory.name %> </h3>
            <% if @user.director %>
                <h6>Cargo: Diretor</h6>
            <% else %>
                <h6>Cargo: Acessor</h6>
            <%end%>
        <%else%>
            <h3>Diretoria: </h3> Você ainda nāo estaá participando de uma diretoria <br>
            <%= link_to 'ver diretorias', directories_path , :class =>"classlink"%>
        <%end%>
        <h3>Células:</h3>
        <%if !@user.cells.nil? %>
            <% @user.cells.each do |c|%>
                <%=c.name%><br>
                <%= c.description %>
            <% end %>
        <%else%>
            <%= link_to 'ver células', cells_path , :class =>"classlink"%>
        <% end %>


        <h3>Meus artigos</h3>

        <% @posts.each do |post| %>
            <%= post.name %><br>
            <%= post.body %><br>
        <% end %>

        <%= link_to 'publicar um artigo', new_post_path , :class =>"classlink"%>


        <h3>Minhas perguntas</h3>
        <% @questions.each do |question| %>
            Título: <%= question.name %><br>
            <%= question.body %><br>
        <% end %>

        <%= link_to 'Fazer uma pergunta', new_question_path , :class =>"classlink"%>
    </div>
</section>