config/routes.rb
Rails.application.routes.draw do
  
  resources :projects
  resources :roles
  resources :cells
  get 'directories/index'

  get 'directories/show'

  devise_for :users

  resources :questions do
    member do
      put "like", to: "questions#upvote"
      put "dislike", to: "questions#downvote"
    end
  end
  
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end


  get '/home', to: "home#index"
  root :to => "home#index"
  

  post "/post_comment/", to: "post_comments#create", as: :post_comments
  post "/question_comment/", to: "question_comments#create", as: :question_comments

  #diretorias
  get "/directories", to: "directories#index", as: :directories
  get "/directory/:id", to: "directories#show", as: :directory
  get "directories/new", to: "directories#new", as: :new_directory
  post "directories/", to: "directories#create", as: :create_directory
  delete "directory/:id", to: "directories#destroy", as: :remove_directory


  post "/enter_directory", to: "directories#enter_directory", as: :enter_directory
  post "/fusion_ask", to: "directories#fusion_ask", as: :fusion_ask
  get "/fusion_ask_requests", to: "directories#fusion_ask_request", as: :fusion_ask_request
  post "/fusion_ask_accept", to: "directories#fusion_ask_accept", as: :fusion_ask_accept
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #cell
  post "/participate_cell", to: "cells#participate_cell", as: :participate_cell

  #projects
  post "/enter_project", to: "projects#enter_project", as: :enter_project
  post "/accept_request", to: "projects#accept_project_requests", as: :accept_project_requests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cell.rb
class Cell < ApplicationRecord
    has_many :users

    has_many :user_cells
    has_many :users, through: :user_cells
    
end

app/models/directory.rb
class Directory < ApplicationRecord
    has_many :users
    has_many :fusion_asks
end

app/models/fusion_ask.rb
class FusionAsk < ApplicationRecord
  belongs_to :user
  belongs_to :directory
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :delete_all
  acts_as_votable
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :user_projects
    has_many :users, through: :user_projects

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :question_comments, dependent: :delete_all
  acts_as_votable
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  has_many :questions

  has_many :post_comments

  belongs_to :directory, optional: true
  has_many :fusion_asks
  
  has_many :user_cells, dependent: :delete_all
  has_many :cells, through: :user_cells
  
  has_many :user_projects, dependent: :delete_all
  has_many :projects, through: :user_projects


  acts_as_voter

end

app/models/user_cell.rb
class UserCell < ApplicationRecord
  belongs_to :user
  belongs_to :cell
end

app/models/user_project.rb
class UserProject < ApplicationRecord

  belongs_to :user
  belongs_to :project
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index

    @user = current_user
    @posts = @user.posts
    @questions = @user.questions
    
    
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @user = current_user
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    
    @user_projects = @project.user_projects
    @members = @project.users
    @user = current_user
    @projects = @user.projects
    @has_project = false

    @projects.each do |p|
      if p == @project 
        @has_project = true
      end
    end
  end

  # GET /projects/new
  def new
    @user = current_user
    @project = Project.new
    
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def enter_project
    
    @user_project = UserProject.create(project_id:params[:project_id], user_id:params[:user_id], status:false)
    redirect_to project_path(params[:project_id])
  end

  def accept_project_requests
    @user_project = UserProject.find(params[:user_project_id])
    @user_project.status = true
    @user_project.save
    redirect_to project_path(@project.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :tecnologies, :begining_date, :expected_end_date, :end_date, :manager)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/projects/_enter_project_requests.html.erb
<h4>Solicitacoes de entrar em projeto </h4>

<% @user_projects.each do |up| %>
    <%= up.user.email %>
    <% if !up.status %>
        <%= link_to 'aceitar', accept_project_requests_path(:user_project_id => up.id), method: :post %><br>
    <% else %>
        membro aceito
    <% end %>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_description %>
  </div>

  <div class="field">
    <%= form.label :tecnologies %>
    <%= form.text_area :tecnologies, id: :project_tecnologies %>
  </div>

  <div class="field">
    <%= form.label :begining_date %>
    <%= form.datetime_select :begining_date, id: :project_begining_date %>
  </div>

  <div class="field">
    <%= form.label :expected_end_date %>
    <%= form.datetime_select :expected_end_date, id: :project_expected_end_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date, id: :project_end_date %>
  </div>

  <div class="field">
  <%= form.hidden_field :manager,id: :project_manager, value: @user.email %>
  
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<section class="artigos">
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Mostrar', @project , :class => "classlink"%> 
<%= link_to 'Voltar', projects_path , :class => "classlink"%>
</section>

app/views/projects/index.html.erb
<section class="artigos">
<p id="notice"><%= notice %></p>

<h1>Projetos<%=image_tag("whiteboard.png", alt:"foto teste")%></h1>

      <th>Nome</th>
      <th>Descrição</th>
      <th>Tecnologias empregadas</th>
      <th>Data inicial</th>
      <th>Data final esperada</th>
      <th>Data final</th>
      <th>Coordenador</th>
      <th colspan="3"></th>
   
 

  <div="containerindex">
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.tecnologies %></td>
        <td><%= project.begining_date %></td>
        <td><%= project.expected_end_date %></td>
        <td><%= project.end_date %></td>
        <td><%= project.manager %></td>
        <td><%= link_to 'Show', project %></td>
        <% if project.manager == @user.email %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
    
  </div>
  <br><br><%= link_to 'New Project', new_project_path, :class =>"classlink"%>
</section>

<br>

app/views/projects/new.html.erb
<section class="artigos">
    <h1>New Project</h1>

    <%= render 'form', project: @project %>

    <%= link_to 'Voltar', projects_path %>
</section>

app/views/projects/show.html.erb
<section class="artigos">
<p id="notice"><%= notice %></p>
<%is_manager = @user.email == @project.manager%>
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Tecnologies:</strong>
  <%= @project.tecnologies %>
</p>

<p>
  <strong>Begining date:</strong>
  <%= @project.begining_date %>
</p>

<p>
  <strong>Expected end date:</strong>
  <%= @project.expected_end_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @project.end_date %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @project.manager %><br>
  
  <strong>Members:</strong><br>
  <% @members.each do |m| %>
    member: <%= m.email %><br>
  <% end %>
</p>
<% if !@has_project %>
  <%= link_to 'Participar do projeto', enter_project_path(:project_id => @project.id, :user_id => @user.id), :class => "classlink", method: :post %> 
<% else %>
  Voce participa deste projeto
  <h3></h3>
<% end %>
<%= link_to 'Editar', edit_project_path(@project) , :class => "classlink"%> 
<%= link_to 'Voltar', projects_path , :class => "classlink"%>

<% if @user.email == @project.manager %>
  <%= render "enter_project_requests"%>
<%end%>

</section>