config/routes.rb
Rails.application.routes.draw do
  
  resources :projects
  resources :roles
  resources :cells
  get 'directories/index'

  get 'directories/show'

  devise_for :users

  resources :questions do
    member do
      put "like", to: "questions#upvote"
      put "dislike", to: "questions#downvote"
    end
  end
  
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end


  get '/home', to: "home#index"
  root :to => "home#index"
  

  post "/post_comment/", to: "post_comments#create", as: :post_comments
  post "/question_comment/", to: "question_comments#create", as: :question_comments

  #diretorias
  get "/directories", to: "directories#index", as: :directories
  get "/directory/:id", to: "directories#show", as: :directory
  get "directories/new", to: "directories#new", as: :new_directory
  post "directories/", to: "directories#create", as: :create_directory
  delete "directory/:id", to: "directories#destroy", as: :remove_directory


  post "/enter_directory", to: "directories#enter_directory", as: :enter_directory
  post "/fusion_ask", to: "directories#fusion_ask", as: :fusion_ask
  get "/fusion_ask_requests", to: "directories#fusion_ask_request", as: :fusion_ask_request
  post "/fusion_ask_accept", to: "directories#fusion_ask_accept", as: :fusion_ask_accept
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #cell
  post "/participate_cell", to: "cells#participate_cell", as: :participate_cell

  #projects
  post "/enter_project", to: "projects#enter_project", as: :enter_project
  post "/accept_request", to: "projects#accept_project_requests", as: :accept_project_requests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cell.rb
class Cell < ApplicationRecord
    has_many :users

    has_many :user_cells
    has_many :users, through: :user_cells
    
end

app/models/directory.rb
class Directory < ApplicationRecord
    has_many :users
    has_many :fusion_asks
end

app/models/fusion_ask.rb
class FusionAsk < ApplicationRecord
  belongs_to :user
  belongs_to :directory
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :delete_all
  acts_as_votable
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :user_projects
    has_many :users, through: :user_projects

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :question_comments, dependent: :delete_all
  acts_as_votable
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  has_many :questions

  has_many :post_comments

  belongs_to :directory, optional: true
  has_many :fusion_asks
  
  has_many :user_cells, dependent: :delete_all
  has_many :cells, through: :user_cells
  
  has_many :user_projects, dependent: :delete_all
  has_many :projects, through: :user_projects


  acts_as_voter

end

app/models/user_cell.rb
class UserCell < ApplicationRecord
  belongs_to :user
  belongs_to :cell
end

app/models/user_project.rb
class UserProject < ApplicationRecord

  belongs_to :user
  belongs_to :project
  
end

app/controllers/cells_controller.rb
class CellsController < ApplicationController
  before_action :set_cell, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /cells
  # GET /cells.json
  def index
    @cells = Cell.all
  end

  # GET /cells/1
  # GET /cells/1.json
  def show
    @user = current_user
    @cells = @user.cells

    
    @cells.each do |cell|
      @has_cell = false
      if cell.id == @cell.id
        @has_cell = true
      end
    end
    
  end

  # GET /cells/new
  def new
    @cell = Cell.new
  end

  def participate_cell
    
    @user_cell = UserCell.create(user_id:params[:user_id], cell_id:params[:cell_id])
    redirect_to cell_path(params[:cell_id])
  end

  # GET /cells/1/edit
  def edit
  end

  # POST /cells
  # POST /cells.json
  def create
    @cell = Cell.new(cell_params)

    respond_to do |format|
      if @cell.save
        format.html { redirect_to @cell, notice: 'Cell was successfully created.' }
        format.json { render :show, status: :created, location: @cell }
      else
        format.html { render :new }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cells/1
  # PATCH/PUT /cells/1.json
  def update
    respond_to do |format|
      if @cell.update(cell_params)
        format.html { redirect_to @cell, notice: 'Cell was successfully updated.' }
        format.json { render :show, status: :ok, location: @cell }
      else
        format.html { render :edit }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cells/1
  # DELETE /cells/1.json
  def destroy
    @cell.destroy
    respond_to do |format|
      format.html { redirect_to cells_url, notice: 'Cell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cell
      @cell = Cell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cell_params
      params.require(:cell).permit(:name, :description)
    end
    

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index

    @user = current_user
    @posts = @user.posts
    @questions = @user.questions
    
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/cells/_form.html.erb
<%= form_with(model: cell, local: true) do |form| %>
  <% if cell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cell.errors.count, "error") %> prohibited this cell from being saved:</h2>

      <ul>
      <% cell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cell_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :cell_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cells/edit.html.erb
<section class="artigos">
    <div class="containerindex">
        <h1>Editando célula</h1>

        <%= render 'form', cell: @cell , :class =>"classlink"%>

        <%= link_to 'Mostrar', @cell , :class =>"classlink"%> 
        <%= link_to 'Voltar', cells_path , :class =>"classlink"%>
    </div>
</section>

app/views/cells/index.html.erb
<section class="artigos">
<p id="notice"><%= notice %></p>

<h1>Células<%=image_tag("connection.png", alt:"foto teste")%></h1>
  <div class="diretoriaindex">
    
      
        <% @cells.each do |cell| %>
          <div class="cadaDiretoria">
            <p><%= cell.name %></p>
            <p><%= cell.description %></p>
            <p><%= link_to 'Mostrar', cell , :class => "classlink"%></p>
            <p><%= link_to 'Editar', edit_cell_path(cell) , :class => "classlink"%></p>
            <p><%= link_to 'Remover', cell, :class => "classlink", method: :delete, data: { confirm: 'Are you sure?' } %></p>
          </div>
        <% end %>
      
    
  

  <%= link_to 'Nova célula', new_cell_path, :class => "classlink"%>
  </div>
</section>

app/views/cells/new.html.erb
<section class="artigos">
    <div class="containerindex">
        <h1>New Cell</h1>

        <%= render 'form', cell: @cell , :class =>"classlink"%>

        <%= link_to 'Back', cells_path , :class =>"classlink" %>
    </div>
</section>

app/views/cells/show.html.erb
<section class="artigos">

    <p id="notice"><%= notice %></p>
  <div class="containerindex">
    <p>
      <strong>Name:</strong>
      <%= @cell.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @cell.description %>
    </p>

        

    <% if !@has_cell %>
      <%= link_to 'Participar de célula', participate_cell_path(:cell_id => @cell.id, :user_id => @user.id), :class => "classlink", method: :post %> 
    <%else%>
      Você participa desta célula
    <%end%>
    <%= link_to 'Editar', cell_path(@cell), :class => "classlink" %> 
    <%= link_to 'Voltar', cells_path , :class => "classlink"%>
  </div>
</section>