config/routes.rb
Rails.application.routes.draw do
  
  resources :projects
  resources :roles
  resources :cells
  get 'directories/index'

  get 'directories/show'

  devise_for :users

  resources :questions do
    member do
      put "like", to: "questions#upvote"
      put "dislike", to: "questions#downvote"
    end
  end
  
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end


  get '/home', to: "home#index"
  root :to => "home#index"
  

  post "/post_comment/", to: "post_comments#create", as: :post_comments
  post "/question_comment/", to: "question_comments#create", as: :question_comments

  #diretorias
  get "/directories", to: "directories#index", as: :directories
  get "/directory/:id", to: "directories#show", as: :directory
  get "directories/new", to: "directories#new", as: :new_directory
  post "directories/", to: "directories#create", as: :create_directory
  delete "directory/:id", to: "directories#destroy", as: :remove_directory


  post "/enter_directory", to: "directories#enter_directory", as: :enter_directory
  post "/fusion_ask", to: "directories#fusion_ask", as: :fusion_ask
  get "/fusion_ask_requests", to: "directories#fusion_ask_request", as: :fusion_ask_request
  post "/fusion_ask_accept", to: "directories#fusion_ask_accept", as: :fusion_ask_accept
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #cell
  post "/participate_cell", to: "cells#participate_cell", as: :participate_cell

  #projects
  post "/enter_project", to: "projects#enter_project", as: :enter_project
  post "/accept_request", to: "projects#accept_project_requests", as: :accept_project_requests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cell.rb
class Cell < ApplicationRecord
    has_many :users

    has_many :user_cells
    has_many :users, through: :user_cells
    
end

app/models/directory.rb
class Directory < ApplicationRecord
    has_many :users
    has_many :fusion_asks
end

app/models/fusion_ask.rb
class FusionAsk < ApplicationRecord
  belongs_to :user
  belongs_to :directory
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :delete_all
  acts_as_votable
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :user_projects
    has_many :users, through: :user_projects

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :question_comments, dependent: :delete_all
  acts_as_votable
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  has_many :questions

  has_many :post_comments

  belongs_to :directory, optional: true
  has_many :fusion_asks
  
  has_many :user_cells, dependent: :delete_all
  has_many :cells, through: :user_cells
  
  has_many :user_projects, dependent: :delete_all
  has_many :projects, through: :user_projects


  acts_as_voter

end

app/models/user_cell.rb
class UserCell < ApplicationRecord
  belongs_to :user
  belongs_to :cell
end

app/models/user_project.rb
class UserProject < ApplicationRecord

  belongs_to :user
  belongs_to :project
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoPS</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="container">
    <%=image_tag("logo.png", alt:"foto teste", class:"logo")%>
    <% if user_signed_in? %>
      <%= link_to('Perfil',home_path, :class => "classbutton") %>
      <%= link_to('Artigos', posts_path, :class =>"classbutton") %>
      <%= link_to('Perguntas', questions_path, :class =>"classbutton") %>
      <%= link_to('Diretorias', directories_path, :class => "classbutton") %>
      <%= link_to('Células', cells_path, :class =>"classbutton") %>
      <%= link_to('Projetos', projects_path, :class =>"classbutton") %>
    <div class="atualUsuario">
      <%= current_user.email%>
      <%= link_to('Logout', destroy_user_session_path, method: :delete, :class => "classlogout") %>
    </div>
    <%end%>
    </nav>
    
    <%= yield %>
    
  </body>
</html>